Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2020-09, with the labels that each got.

#14 Update Slack Channel
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13 Add test-infra scripts
  Makefile
  cloudbuild.yaml
  scripts/test-infra/build-image.sh
  scripts/test-infra/build.sh
  scripts/test-infra/push-image.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#15 scripts: make push-image.sh runnable locally
  scripts/test-infra/push-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#16 Use official golang image as BUILDER
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#17 Bumb golang version to 1.14.7
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 Makefile: disable golangci-lint in verify
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#20 Drop trailing whitespace from various files
  Dockerfile
  Makefile
  README.md
  assets/master/0400_master_daemonset.yaml
  assets/worker/0700_worker_daemonset.yaml
  manifests/0700_cr.yaml
  scripts/test-infra/build-image.sh
  scripts/test-infra/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#25 Add RELEASE.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#21 scripts: make golangci-lint runnable in verify.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#22 scripts: update golangci-lint to v1.31.0 in verify.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#27 Update default operand image
  pkg/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Enable issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M, tide/merge-method-squash

#26 fix README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash

#32 Fix golangci-lint verify
  Makefile
  cmd/manager/main.go
  pkg/config/config.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_resources.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#31 Enhance nfd-worker placement
  Makefile
  assets/worker/0700_worker_daemonset.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S, tide/merge-method-squash
