Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2020-12, with the labels that each got.

#39 Expand nodeFeatureDiscovery CRD
  README.md
  go.mod
  go.sum
  manifests/0500_crd.yaml
  manifests/0700_cr.yaml
  pkg/apis/addtoscheme_nfd_v1alpha1.go
  pkg/apis/nfd/v1/doc.go
  pkg/apis/nfd/v1/nodefeaturediscovery_types.go
  pkg/apis/nfd/v1/register.go
  pkg/apis/nfd/v1/zz_generated.deepcopy.go
  pkg/apis/nfd/v1/zz_generated.openapi.go
  pkg/apis/nfd/v1alpha1/doc.go
  pkg/config/config.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controller.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#40 Bump NFD to V0.7.0
  manifests/0600_operator.yaml
  manifests/0700_cr.yaml
  pkg/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#42 fix wrong variable naming leading to failing deployment
  manifests/0500_crd.yaml
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#43 github: add issue template for new releases
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, cncf-cla: yes, lgtm, size/M
