Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2021-10, with the labels that each got.

#92 scripts/test-infra: bump golangci-lint to v1.42.1
  scripts/test-infra/verify.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm, hacktoberfest

#93 Migrate loggin to klogv2
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_resources.go
  go.mod
  go.sum
  main.go
Labels: approved, size/L, cncf-cla: yes, lgtm, hacktoberfest

#95 go.mod: update controller-runtime to v0.10.2
  go.mod
  go.sum
Labels: approved, size/L, cncf-cla: yes, lgtm, hacktoberfest-accepted
