Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2021-08, with the labels that each got.

#78 Add BASE_IMAGE_FULL build arg
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, size/S, lgtm

#80 Use apimachinery error library to check for missing nfd instance
  controllers/nodefeaturediscovery_controller.go
Labels: approved, size/XS, cncf-cla: yes, ok-to-test, lgtm

#76 add support for config IMAGE_TAG and rbac proxy image
  Makefile
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, size/M, ok-to-test, lgtm

#83 Bump Dockerfile to go 1.16.7
  Dockerfile
Labels: approved, size/XS, cncf-cla: yes, lgtm

#82 Add minimal image
  Dockerfile
  Makefile
  docs/advanced/developer-guide.md
  docs/get-started/quick-start.md
  scripts/test-infra/build-image.sh
  scripts/test-infra/push-image.sh
Labels: approved, cncf-cla: yes, size/M, lgtm
