Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2021-04, with the labels that each got.

#52 assets/worker: do not user host network
  build/assets/worker/05_worker_ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#57 Minor fixes after upgrading operator sdk
  config/manager/manager.yaml
  controllers/nodefeaturediscovery_state.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#55 Bump go version to 1.16
  Dockerfile
  config/manager/kustomization.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#58 Use upstream image
  config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#59 Sync Makefile with NFD Operand
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#60 Add support for Core-Config
  api/v1/nodefeaturediscovery_types.go
  api/v1/zz_generated.deepcopy.go
  build/assets/worker/04_worker_cm.yaml
  build/assets/worker/05_worker_ds.yaml
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#61 Add kustomize patch for ClusterRole
  config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#62 Add kustomize rule for commonAnnotations on CRD
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#63 Add serviceport var to CRD
  api/v1/nodefeaturediscovery_types.go
  build/assets/master/0400_master_daemonset.yaml
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
  controllers/nodefeaturediscovery_controls.go
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#56 add support for NFD-Master instance flag
  api/v1/nodefeaturediscovery_types.go
  build/assets/master/0400_master_daemonset.yaml
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  controllers/nodefeaturediscovery_controls.go
Labels: approved, cncf-cla: yes, lgtm, size/S
