Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2022-05, with the labels that each got.

#150 github: update release issue template
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, cncf-cla: yes, size/S, lgtm

#151 controller: fix nfd-master cmdline args
  controllers/nodefeaturediscovery_controls.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#155 Minor updates to kustomize set image
  .gitignore
  Makefile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  go.mod
  go.sum
Labels: approved, size/L, cncf-cla: yes, lgtm

#156 build/assets comply to restricted pod security level
  build/assets/master/0400_master_deployment.yaml
  build/assets/worker/05_worker_ds.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm

#157 Swap default image to Minimal
  Makefile
  config/manifests/bases/nfd-operator.clusterserviceversion.yaml
  docs/_config.yml
  docs/get-started/quick-start.md
Labels: approved, cncf-cla: yes, size/S, lgtm
