Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2022-04, with the labels that each got.

#139 scripts/test-infra: bump golangci-lint to v1.45.2
  scripts/test-infra/verify.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#135 Bump Go to 1.18
  Dockerfile
  go.mod
  go.sum
Labels: approved, size/XS, cncf-cla: yes, lgtm

#142 Dockerfile: update builder image to Go v1.18.1
  Dockerfile
Labels: approved, size/XS, cncf-cla: yes, lgtm

#143 Update kubebuilder crd generation
  Makefile
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm

#141 Run nfd-master as Deployment
  build/assets/master/0400_master_daemonset.yaml
  build/assets/master/0400_master_deployment.yaml
  build/assets/master/0500_service.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/nfd-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/rbac/role.yaml
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_finalizers.go
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_status.go
Labels: approved, size/L, cncf-cla: yes, lgtm

#144 Update kubebuilder rbac
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/nodefeaturediscovery_controller.go
Labels: approved, size/L, cncf-cla: yes, lgtm

#145 Cherry/0.4.2
  build/assets/master/0400_master_daemonset.yaml
  build/assets/master/0400_master_deployment.yaml
  build/assets/master/0500_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_finalizers.go
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_status.go
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, size/XL, lgtm

#147 Update docs for 0.4.2
  docs/_config.yml
Labels: approved, size/XS, cncf-cla: yes, lgtm
