Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2022-01, with the labels that each got.

#103 Updated the links in contributing page
  docs/contributing/index.md
Labels: approved, size/XS, cncf-cla: yes, ok-to-test, lgtm

#99 Drop the non-working link from the Advanced section
  docs/advanced/nodefeaturediscovery.md
Labels: approved, size/XS, cncf-cla: yes, ok-to-test, lgtm

#108 release-0.2: docs: drop invalid step from deployment instructions
  docs/advanced/developer-guide.md
  docs/get-started/quick-start.md
Labels: approved, cncf-cla: yes, size/S, lgtm

#109 docs: link to correct version of operand docs
  docs/_includes/templates/sidebar.liquid
Labels: approved, size/XS, cncf-cla: yes, lgtm

#110 docs: sync CR example with config/samples/
  docs/advanced/nodefeaturediscovery.md
Labels: approved, size/XS, cncf-cla: yes, lgtm

#111 release-0.3: fixes to docs
  docs/_config.yml
  docs/advanced/nodefeaturediscovery.md
Labels: approved, cncf-cla: yes, size/S, lgtm
