Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2023-03, with the labels that each got.

#183 scripts/test-infra: bump golangci-lint to v1.51.2
  controllers/nodefeaturediscovery_finalizers.go
  pkg/utils/utils.go
  scripts/test-infra/verify.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#182 go.mod: update kubernetes to v1.26.2
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/M, lgtm

#185 HELM: update-gh-pages.sh to create chart index
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, size/M, lgtm

#188 Enable automated Prune via CRD NodeFeatureDiscoveries
  api/v1/nodefeaturediscovery_types.go
  build/assets/prune/0100_service_account.yaml
  build/assets/prune/0200_clusterrole.yaml
  build/assets/prune/0300_clusterole_binding.yaml
  build/assets/prune/0400_prune_job.yaml
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_finalizers.go
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_status.go
  deploy/helm/nfd-operator/crds/nfd-api-crds.yaml
Labels: approved, size/L, cncf-cla: yes, lgtm

#190 values.yml: revert change on line 19
  deploy/helm/nfd-operator/values.yaml
Labels: approved, size/XS, cncf-cla: yes, lgtm

#191 Bump release to v0.6.0
  README.md
  api/v1/nodefeaturediscovery_types.go
  bundle/manifests/nfd-operator.clusterserviceversion.yaml
  bundle/manifests/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/nfd-operator.clusterserviceversion.yaml
  config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
  deploy/helm/nfd-operator/Chart.yaml
  deploy/helm/nfd-operator/crds/nfd-api-crds.yaml
  deploy/helm/nfd-operator/templates/deployment.yaml
  deploy/helm/nfd-operator/values.yaml
  docs/_config.yml
Labels: approved, cncf-cla: yes, size/M, lgtm

#193 Lesson learned from v0.6 cut
  .github/ISSUE_TEMPLATE/release.md
  Dockerfile
  README.md
  RELEASE.md
  api/v1/nodefeaturediscovery_types.go
  bundle/manifests/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  bundle/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/nfd-operator.clusterserviceversion.yaml
  config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
  deploy/helm/nfd-operator/crds/nfd-api-crds.yaml
  deploy/helm/nfd-operator/templates/deployment.yaml
Labels: approved, size/L, cncf-cla: yes, lgtm
