Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2023-01, with the labels that each got.

#168 [release-0.5] docs: fix operand version
  Makefile
  docs/_config.yml
  scripts/test-infra/mdlint.sh
Labels: approved, cncf-cla: yes, size/S, lgtm

#170 Update dependencies to sync with Operand
  .gitignore
  Dockerfile
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XL, lgtm

#171 Deprecation of package ioutil
  controllers/nodefeaturediscovery_resources.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#173 dockerfile: builder image configurable through a Makefile variable.
  Dockerfile
  Makefile
Labels: approved, size/XS, cncf-cla: yes, lgtm

#176 Update project OWNERS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, size/XS, cncf-cla: yes, lgtm

#172 Update README to be more welcoming
  README.md
Labels: approved, cncf-cla: yes, size/M, lgtm

#177 Dockerfile: define numeric user to run unprivileged
  .gitignore
  Dockerfile
Labels: approved, size/XS, cncf-cla: yes, lgtm

#178 README: fix documentation link
  README.md
Labels: approved, size/XS, cncf-cla: yes, lgtm
