Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2024-06, with the labels that each got.

#235 sync nodefeaturerules crd config with helm
  config/crd/bases/nfd.k8s-sigs.io_v1alpha1_nodefeaturerules.yaml
Labels: approved, cncf-cla: yes, size/M, ok-to-test, lgtm

#237 add enableTaints option to enable taint support in the crd
  api/v1/nodefeaturediscovery_types.go
  config/crd/bases/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
  deploy/helm/nfd-operator/crds/nfd-api-crds.yaml
  internal/deployment/deployment.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S, lgtm

#234 Adding NFD CR status handling
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
  internal/status/mock_status.go
  internal/status/status.go
  internal/status/status_test.go
  internal/status/suite_test.go
  main.go
Labels: approved, cncf-cla: yes, size/XXL, lgtm

#236 sync operator nfr crds with operand helm nfr crds
  config/crd/bases/nfd.k8s-sigs.io_v1alpha1_nodefeaturerules.yaml
  config/crd/bases/nfd.kubernetes.io_v1alpha1_nodefeaturerules.yaml
  config/manifests/bases/nfd-operator.clusterserviceversion.yaml
  config/samples/nodefeaturerules.nfd.k8s-sigs.io_v1alpha1_nodefeaturerules.yaml
  deploy/helm/nfd-operator/crds/nfd-api-crds.yaml
Labels: approved, size/L, cncf-cla: yes, ok-to-test, lgtm

#238 Getting rid of pkg/utils
  main.go
Labels: approved, cncf-cla: yes, size/S, lgtm

#240 Getting rid of pkg/version
  Makefile
  main.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#241 Removing old/unused packages
  Dockerfile
  build/assets/gc/clusterrole.yaml
  build/assets/gc/clusterrolebinding.yaml
  build/assets/gc/deployment.yaml
  build/assets/gc/serviceaccount.yaml
  build/assets/master/0100_service_account.yaml
  build/assets/master/0200_clusterrole.yaml
  build/assets/master/0300_clusterrole_binding.yaml
  build/assets/master/0400_master_deployment.yaml
  build/assets/master/0500_service.yaml
  build/assets/prune/0100_service_account.yaml
  build/assets/prune/0200_clusterrole.yaml
  build/assets/prune/0300_clusterole_binding.yaml
  build/assets/prune/0400_prune_job.yaml
  build/assets/topologyupdater/01_sa.yaml
  build/assets/topologyupdater/02_clusterrole.yaml
  build/assets/topologyupdater/03_clusterrolebinding.yaml
  build/assets/topologyupdater/05_Daemonset.yaml
  build/assets/worker/01_worker_sa.yaml
  build/assets/worker/02_worker_role.yaml
  build/assets/worker/03_worker_rolebinding.yaml
  build/assets/worker/04_worker_cm.yaml
  build/assets/worker/05_worker_ds.yaml
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_finalizers.go
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_state.go
  controllers/nodefeaturediscovery_status.go
  controllers/suite_test.go
  pkg/utils/utils.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, size/XXL, lgtm

#242 add nodefeaturegroups support
  config/crd/bases/nfd.k8s-sigs.io_nodefeaturegroups.yaml
  config/crd/kustomization.yaml
  config/rbac/master/clusterrole.yaml
Labels: approved, size/L, cncf-cla: yes, ok-to-test, lgtm

#243 sync helm chart crds/rbac with the kustomize files
  deploy/helm/nfd-operator/crds/nfd-api-crds.yaml
  deploy/helm/nfd-operator/crds/nfd.k8s-sigs.io_nodefeaturegroups.yaml
  deploy/helm/nfd-operator/crds/nfd.k8s-sigs.io_nodefeatures.yaml
  deploy/helm/nfd-operator/crds/nfd.k8s-sigs.io_v1alpha1_nodefeaturerules.yaml
  deploy/helm/nfd-operator/crds/nfd.kubernetes.io_nodefeaturediscoveries.yaml
  deploy/helm/nfd-operator/crds/node.k8s.io_v1alpha1_noderesourcetopologies.yaml
  deploy/helm/nfd-operator/templates/rbac.yaml
  deploy/helm/nfd-operator/templates/rbac/auth_proxy/client_clusterrole.yaml
  deploy/helm/nfd-operator/templates/rbac/auth_proxy/role.yaml
  deploy/helm/nfd-operator/templates/rbac/auth_proxy/role_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/auth_proxy/service.yaml
  deploy/helm/nfd-operator/templates/rbac/core/leader_election_role.yaml
  deploy/helm/nfd-operator/templates/rbac/core/leader_election_role_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/core/manager_role.yaml
  deploy/helm/nfd-operator/templates/rbac/core/manager_role.yaml.working
  deploy/helm/nfd-operator/templates/rbac/core/manager_role_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/gc/clusterrole.yaml
  deploy/helm/nfd-operator/templates/rbac/gc/clusterrole_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/gc/sa.yaml
  deploy/helm/nfd-operator/templates/rbac/master/clusterrole.yaml
  deploy/helm/nfd-operator/templates/rbac/master/clusterrole_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/master/sa.yaml
  deploy/helm/nfd-operator/templates/rbac/nodefeaturediscovery_editor_role.yaml
  deploy/helm/nfd-operator/templates/rbac/nodefeaturediscovery_viewer_role.yaml
  deploy/helm/nfd-operator/templates/rbac/prune/clusterrole.yaml
  deploy/helm/nfd-operator/templates/rbac/prune/clusterrole_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/prune/sa.yaml
  deploy/helm/nfd-operator/templates/rbac/topologyupdater/clusterrole.yaml
  deploy/helm/nfd-operator/templates/rbac/topologyupdater/clusterrole_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/topologyupdater/sa.yaml
  deploy/helm/nfd-operator/templates/rbac/worker/role.yaml
  deploy/helm/nfd-operator/templates/rbac/worker/role_binding.yaml
  deploy/helm/nfd-operator/templates/rbac/worker/sa.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/XXL, lgtm
