Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2024-04, with the labels that each got.

#218 Add worker daemonsets to refactored reconcile loop
  internal/configmap/configmap.go
  internal/configmap/configmap_test.go
  internal/configmap/mock_configmap.go
  internal/configmap/suite_test.go
  internal/configmap/testdata/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
  internal/configmap/testdata/test_worker_configmap.yaml
  internal/controllers/mock_nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/daemonset/testdata/test_worker_daemonset.yaml
  internal/daemonset/worker.go
  internal/deployment/mock_deployment.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL, lgtm

#219 Adding GC deployment implementation
  internal/configmap/mock_configmap.go
  internal/controllers/mock_nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
  internal/daemonset/mock_daemonset.go
  internal/deployment/deployment.go
  internal/deployment/deployment_test.go
  internal/deployment/mock_deployment.go
  internal/deployment/testdata/test_gc_deployment.yaml
Labels: approved, size/L, cncf-cla: yes, lgtm

#220 setting finalizer on the NFD CR
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
Labels: approved, cncf-cla: yes, size/M, lgtm

#223 adding unit-tests for handling worker flow
  internal/controllers/nodefeaturediscovery_reconciler_test.go
Labels: approved, size/L, cncf-cla: yes, lgtm

#221 set permissions for the refactored controller
  config/crd/bases/nfd.k8s-sigs.io_nodefeatures.yaml
  config/crd/bases/nfd.k8s-sigs.io_v1alpha1_nodefeaturerules.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy/client_clusterrole.yaml
  config/rbac/auth_proxy/kustomization.yaml
  config/rbac/auth_proxy/role.yaml
  config/rbac/auth_proxy/role_binding.yaml
  config/rbac/auth_proxy/service.yaml
  config/rbac/core/kustomization.yaml
  config/rbac/core/leader_election_role.yaml
  config/rbac/core/leader_election_role_binding.yaml
  config/rbac/core/manager_role.yaml
  config/rbac/core/manager_role.yaml.working
  config/rbac/core/manager_role_binding.yaml
  config/rbac/gc/clusterrole.yaml
  config/rbac/gc/clusterrole_binding.yaml
  config/rbac/gc/kustomization.yaml
  config/rbac/gc/sa.yaml
  config/rbac/kustomization.yaml
  config/rbac/master/clusterrole.yaml
  config/rbac/master/clusterrole_binding.yaml
  config/rbac/master/kustomization.yaml
  config/rbac/master/sa.yaml
  config/rbac/nodefeaturediscovery_viewer_role.yaml
  config/rbac/prune/clusterrole.yaml
  config/rbac/prune/clusterrole_binding.yaml
  config/rbac/prune/kustomization.yaml
  config/rbac/prune/sa.yaml
  config/rbac/topologyupdater/clusterrole.yaml
  config/rbac/topologyupdater/clusterrole_binding.yaml
  config/rbac/topologyupdater/kustomization.yaml
  config/rbac/topologyupdater/sa.yaml
  config/rbac/worker/kustomization.yaml
  config/rbac/worker/role.yaml
  config/rbac/worker/role_binding.yaml
  config/rbac/worker/sa.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/XL, lgtm

#222 adding finalizer flow
  internal/configmap/configmap.go
  internal/configmap/configmap_test.go
  internal/configmap/mock_configmap.go
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
  internal/daemonset/daemonset.go
  internal/daemonset/daemonset_test.go
  internal/daemonset/mock_daemonset.go
  internal/deployment/deployment.go
  internal/deployment/deployment_test.go
  internal/deployment/mock_deployment.go
Labels: approved, size/L, cncf-cla: yes, lgtm

#224 Adding prune job to the finalization flow
  internal/controllers/mock_nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
  internal/job/job.go
  internal/job/job_test.go
  internal/job/mock_job.go
  internal/job/suite_test.go
  internal/job/testdata/test_prune_job.yaml
Labels: approved, cncf-cla: yes, size/XL, lgtm

#225 adding golangci-lint to the skipper Dockerfile
  Dockerfile.node-feature-discovery-operator-build
  Makefile
Labels: approved, size/XS, cncf-cla: yes, lgtm
