Repository kubernetes-sigs/node-feature-discovery-operator, pull requests merged in 2024-02, with the labels that each got.

#211 controller-runtime package update
  controllers/nodefeaturediscovery_finalizers.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, size/XL, lgtm

#212 Adding new controller template
  go.mod
  go.sum
  internal/controllers/mock_nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler.go
  internal/controllers/nodefeaturediscovery_reconciler_test.go
  internal/controllers/suite_test.go
  internal/test/scheme.go
Labels: approved, cncf-cla: yes, size/XL, lgtm

#216 OWNERS: add yevgeny-shnaidman as a reviewer
  OWNERS
Labels: approved, size/XS, cncf-cla: yes, lgtm

#215 skipperizing the repo
  Dockerfile.node-feature-discovery-operator-build
  docs/advanced/developer-guide.md
  skipper.env
  skipper.yaml
Labels: approved, cncf-cla: yes, size/M, lgtm

#207 scripts/test-infra: add unit-tests.sh
  scripts/test-infra/unit-tests.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm
